version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  chainlit:
    build: .
    container_name: chainlit
    command: chainlit run cibbot.py --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - qdrant
    restart: unless-stopped

volumes:
  qdrant_data:
